# Generated by Django 5.0.3 on 2024-06-10 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statment',
            name='set_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 45, 16, 172881, tzinfo=datetime.timezone.utc), verbose_name='Выбрать время'),
        ),
    ]
