# Generated by Django 5.0.3 on 2024-06-10 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_statment_set_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statment',
            name='user',
        ),
        migrations.AlterField(
            model_name='statment',
            name='set_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 59, 1, 676516, tzinfo=datetime.timezone.utc), verbose_name='Выбрать время'),
        ),
    ]
