# Generated by Django 5.0.3 on 2024-06-10 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_statment_user_alter_statment_set_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statment',
            name='status',
        ),
        migrations.AlterField(
            model_name='statment',
            name='set_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 14, 8, 52, 523673, tzinfo=datetime.timezone.utc), verbose_name='Выбрать время'),
        ),
    ]
