# Generated by Django 5.0.3 on 2024-06-10 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_statment_status_alter_statment_set_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Название')),
                ('description', models.CharField(max_length=254, verbose_name='Описание')),
                ('price', models.CharField(max_length=254, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='service_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='statment',
            name='set_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 14, 13, 15, 533224, tzinfo=datetime.timezone.utc), verbose_name='Выбрать время'),
        ),
    ]
