# Generated by Django 5.0.6 on 2024-06-13 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_service_alter_statment_set_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=254, verbose_name='Почта или телефон')),
                ('description', models.CharField(max_length=254, verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AlterField(
            model_name='statment',
            name='set_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 9, 46, 48, 940760, tzinfo=datetime.timezone.utc), verbose_name='Выбрать время'),
        ),
    ]
