# Generated by Django 5.0.6 on 2024-06-13 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_statment_set_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statment',
            name='set_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 10, 58, 40, 128586, tzinfo=datetime.timezone.utc), verbose_name='Выбрать время'),
        ),
    ]
