# Generated by Django 5.0.6 on 2024-06-13 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_statment_set_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statment',
            name='set_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 11, 2, 56, 870186, tzinfo=datetime.timezone.utc), verbose_name='Выбрать время'),
        ),
    ]
